### PR TITLE
Added Docker integration

### PR DESCRIPTION
**Pull request by lb1c**
Based on https://github.com/ibrahimawadhamid/openlayers-editor/commit/4c1002991a4ed0c110e6b4de1d06ad36821077d7

### CODE REVIEW

**Comment by friedjoff** [comment]
Sorry for not interrupting you guys earlier, but I'm not convinced we need Docker integration. This is a simple JavaScript project, which only requires NodeJS for running. @mhaertwig or @oterral what do you think?

**Comment by lb1c** [comment]
In my opinion it's nice to have a quick up and running example (like the demo page)..

**Comment by friedjoff** [comment]
Yeah, just run `npm install && npm start` 😉

**Comment by lb1c** [comment]
Which may or may not break, depending on node version, npm version etc.
Having a static reference and the ability to include the editor via compose or `copy-from` into other stuff is worth the already done work.

**Comment by ibrahimawadhamid** [comment]
> Which may or may not break, depending on node version, npm version etc.
> Having a static reference and the ability to include the editor via compose or `copy-from` into other stuff is worth the already done work.
> Edit: Also don't forget the windows users out there, who may not know terminals exist. (but docker for windows does 😜 )

I second that (Y)

**Comment by oterral** [comment]
why not. If somebody needs it.  

> Edit: Also don't forget the windows users out there, who may not know terminals exist. (but docker for windows does stuck_out_tongue_winking_eye )

Do you really think someone that does not know terminals exist.,knows that docker exists ? :)

**Pull request closed without merging**
